theme: jekyll-theme-leap-day

头像： https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/avatar.png # 网站标志
background： # 既是博客的背景，又是文章默认头图
路径： https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/cover/5c3aec85a4343.jpg
宽度： 1440
高度： 960
图标：
href： /favicon.ico # 网站图标
类型： image/x-icon # 图标类型，可能的值有（image/png， image/vnd.microsoft.icon， image/x-icon， image/gif）

function： # 功能开关，可选值（true，false）
globalToc： false # 开启该功能会自动开启文章 TOC（文章目录） 功能

# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
图标： # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

darkmode： true # 是否启用暗色主题，可选值（true，false）

产品搜索：
类型： engine # 可选engine（用搜索引擎搜索）或 swiftype
url： https://cn.bing.com/search?q=site:nexmoe.com # 搜索引擎地址，在type为swiftype时无效 e.g：https：//www.google.com/search？q={你的博客链接}
id： <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效

cdn： # 这里可以修改站点使用的库的CDN
disqusjs：
css： https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
js： https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
gitalk：
css： https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.css
js： https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
缬氨酸：
js： https://cdn.jsdelivr.net/npm/valine

菜单：
回到首页：
    - /
    - 图标主页
# 文章归档： # 使用说明：https://docs.nexmoe.com/article/archive
# - /存档.html
# - 图标容器
关于博客：
    - /关于.html
    - 图标信息圈
我的朋友：
- /PY.html # 使用说明：https://docs.nexmoe.com/article/py

小部件：
- 搜索
- 社会的
- 类别
- 标签云
# - 存档#settings： widgetAchive
# - recent_posts
# - 链接#settings： widgetLink

maxTagcloud： 0 # 标签云组件显示的标签数量，0 表示不限制

社交：
QQ群：
    - https://jq.qq.com/?_wv=1027&k=5CfKHun
    - 图标-QQ
    - rgb（249， 174， 8）
    - rgba（249， 174， 8， .1）
哔哩哔哩：
    - https://space.bilibili.com/20238211
    - icon-bilibili
    - rgb（231， 106， 141）
    - rgba（231， 106， 141， .15）
GitHub：
    - https://github.com/nexmoe/
    - icon-github
    - rgb（25， 23， 23）
    - rgba（25， 23， 23， .15）

# 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
site_verification：
谷歌：
百度：

# 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La 统计、百度统计
分析：
google_site_id： #<ID>
gtags_site_id： #<ID>
cnzz_site_id： #<ID>
tencent_site_id： #<ID>
la_site_id： #<ID>
baidu_site_id： #<ID>
gtm_container_id： #<ID>

# 评论框，目前支持 gitalk，gitment，valine，disqus，disqusjs，changyan，livere，DiscussBot 使用 false 可以关闭
评论： 吉托
gitalk：
admin： nexmoe # 拥有对该repo进行操作的 GitHub username
owner： nexmoe # 持有该存储库 的 GitHub 用户名
repo： nexmoe.github.io # 存放评论的 issue 所在的 repo
客户端 ID： 80b2453b6d5f37ad6225 # GitHub 客户端 ID
clientSecret： 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret
gitment：
owner： nexmoe # 持有该存储库 的 GitHub 用户名
repo： nexmoe.github.io # 存放评论的 issue 所在的 repo
客户端 ID： 80b2453b6d5f37ad6225 # GitHub 客户端 ID
clientSecret： 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret
缬氨酸：
appId： <API_ID> # leancloud application app id
appKey： <API_Key> # leancloud application app key
disqus：
短名称： <shortname> # 你的 Disqus 短名称
disqusjs：
短名称： <shortname> # 你的 Disqus 短名称
sitename： <sitename> # 你站点的名称，将会显示在「评论基础模式」的标头 中;该配置应该和 Disqus Admin - Settings - General - Website Name 一致
api： https://disqus.skk.moe/disqus/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
apikey： <api_key> # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个;如果你只需要填入一个 API Key，则可以填入 String 或 Array。
admin： <admin> # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - 设置 - 帐户 - 用户名 获取你的用户名
adminLabel： <adminLabel> # 你想显示在 Disqus 版主徽章 中的文字。该配置应和 Disqus Admin - 设置 - 社区 - 版主徽章文本 相同
长岩：
appid： <APP_ID> # 畅言的 APPID
conf： <CONF> # 畅言的 CONF
thread_key_type： 路径 # 可选 id 或 路径
肝脏：
data_uid： <data_uid> # 你的来必力 UID，可以在来必力后台获取
讨论机器人：
id： <id> # 站点id
评论： 5 # 可能是限制每位用户单页面评论最多条数？
颜色： # 评论框主色调
不喜欢： 0 # 显示差评按钮
图标： 0 # 图标主题
diff： 0 # 每位用户name不同颜色

版权： '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可"
copyTip： "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案，使用 %url 代替当前页面URL， 修改为false禁用

# 小部件行为
widgetAchive： #文章归档组件
archive_type： 'year' #按月展示还是按年展示
show_count： true #是否展示数量

widgetLink： #链接组件
- 标题：<标题>
免疫接种 ： <img_path>
链接 ： <网址>
- 标题：<标题>
免疫接种 ： <img_path>
链接 ： <网址>

# 自定义侧边栏尾部内容
侧边栏： '<br><a target="_blank" href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img src="https://i.dawnlab.me/c0268c1e6cfd0863d6ba35be1575941a.png" width="150px"></a><script data-ad-client="ca-pub-2058306854838448" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>'
